export const fontInfoFromDBDummyData = {
  // _id: new ObjectId(''),
  family: "none",
  displayName: "none",
  coverage: { none: "none" },
  fonts: { none: "none" },
  axes: ["none"],
  description: "none",
  license: "none",
  designers: [{ name: "none", bio: "none", imageUrl: "none" }],
  fontUses: "none",
  category: "none",
  stroke: "none",
  classifications: ["none"],
  lastModified: "none",
  size: -1,
  isNoto: false,
  colorCapabilities: ["none"],
  primaryScript: "none",
  primaryLanguage: "none",
  article: "none",
  variants: ["none"],
  subsets: ["none"],
  files: { none: "none" },
  kind: "none",
  menu: "none",
  linked: ["none"],
  sampleText: { none: "none" },
};
